---
version: "3"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/cab/docker/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      PUID: 1000
      PGID: 1000

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /home/cab/docker/jellyfin/config:/config
      - /data/server/tvshows:/data/tvshows
      - /data/server/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - puid=1000
      - pgid=1000
      - tz=europe/stockholm
    volumes:
      - /home/cab/docker/jellyfin/config:/config
      - /data/server/tvshows:/data/tvshows
      - /data/server/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /home/cab/docker/nextcloud/config:/config
      - /data:/data
    ports:
      - 9443:443
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - WEBUI_PORT=8080
    volumes:
      - /home/cab/docker/qbittorrent/config:/config
      - /data/server/:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  speedtest-tracker:
      image: henrywhitaker3/speedtest-tracker
      container_name: speedtest
      volumes:
          - /home/cab/docker/speedtest/config:/config
      ports:
          - 8765:80
      environment:
          - TZ=Europe/Stockholm
          - PGID=1000
          - PUID=1000
          - OOKLA_EULA_GDPR=true
      logging:
          driver: "json-file"
          options:
             max-file: "10"
             max-size: "200k"
      restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - /home/cab/data/server/vault:/data/
    ports:
      - 8880:80
    restart: unless-stopped

